Feature: Random Integer

  As an Internet user
  I want to get random integer
  So that I could use it for my needs

  @Smoke
  Scenario Outline: Random Integer can be generated
    Given the user is on the Main page
    When user sets "<minValue>" in Min field
    When user sets "<maxValue>" in Max field
    And user presses <Generate> button
    Then random value is generated in chosen range
    And min value is correct in Result section
    And max value is correct in Result section

    Examples:
    | minValue   | maxValue |
    | -500       | 0        |
    | -11        | 2        |
    | -230       | 53102    |
    | 3          | 14       |
    | 57         | 102      |
    | 105        | 1006     |

@New
  Scenario: Random Integer can be generated by Enter
    Given the user is on the Main page
    When user sets "12" in Min field
    When user sets "22" in Max field
    And user presses "ENTER" in Min field 1 times
    Then random value is generated in chosen range
    And min value is correct in Result section
    And max value is correct in Result section

  Scenario: Min and max input fields have correct values
    Given the user is on the Main page
    Then min value has default value in input field
    And max value has default value in input field

  Scenario Outline: Min can be changed by arrow button
    Given the user is on the Main page
    When user sets "12" in Min field
    And user presses "<key>" in Min field <number> times
    Then min value has "<result>" value in input field
    Examples:
      | key     | number   | result  |
      | UP      | 1        | 13      |
      | UP      | 3        | 15      |
      | DOWN    | 1        | 11      |
      | DOWN    | 4        | 8       |

  Scenario Outline: Max can be changed by arrow button
    Given the user is on the Main page
    When user sets "12" in Max field
    And user presses "<key>" in Max field <number> times
    Then max value has "<result>" value in input field
    Examples:
      | key     | number   | result  |
      | UP      | 1        | 13      |
      | UP      | 3        | 15      |
      | DOWN    | 1        | 11      |
      | DOWN    | 4        | 8       |

  Scenario: Default values are used if max min values are not filled
    Given the user is on the Main page
    When user sets "" in Min field
    When user sets "" in Max field
    And user presses <Generate> button
    Then random value is generated in chosen range
    And min value is correct in Result section
    And max value is correct in Result section

  Scenario Outline: Max value is updated if min value is more or equal to max value
    Given the user is on the Main page
    When user sets "<minValue>" in Min field
    When user sets "<maxValue>" in Max field
    And user presses <Generate> button
    Then min value is correct in Result section
    And max value is updated in Result section
    And random value is generated in chosen range

    Examples:
      | minValue   | maxValue |
      | 0          | 0        |
      | -11        | -20       |

  Scenario Outline: Non numeric values are ignored
    Given the user is on the Main page
    When user sets "<minValue>" in Min field
    When user sets "<maxValue>" in Max field
    Then min value has "" value in input field
    Then max value has "" value in input field

    Examples:
      | minValue      | maxValue         |
      | aaa           |  !@#$%^&*()_     |
      | #$%^&*()_     | CVBNM<:OIUYT     |

  Scenario: Min max values are not saved after page refresh
    Given the user is on the Main page
    When user sets "67" in Min field
    When user sets "324" in Max field
    And user refreshes browser page
    Then min value has default value in input field
    Then max value has default value in input field

  Scenario Outline: Border values for min
    Given the user is on the Main page
    When user sets "<minValue>" in Min field
    And user presses <Generate> button
    Then error text is "<errorText>"
    Examples:
      | minValue      | errorText                                                                           |
      | 1000000001    | Error: The maximum value must be an integer in the [-1000000000,1000000000] interval|
      | -1000000001   | Error: The minimum value must be an integer in the [-1000000000,1000000000] interval|

  Scenario Outline: Border values for max
    Given the user is on the Main page
    When user sets "<maxValue>" in Min field
    And user presses <Generate> button
    Then error text is "<errorText>"
    Examples:
      | maxValue      | errorText                                                                           |
      | 1000000001    | Error: The maximum value must be an integer in the [-1000000000,1000000000] interval|
      | -1000000001   | Error: The minimum value must be an integer in the [-1000000000,1000000000] interval|



